# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages  # Name of the GitHub Actions workflow

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]  # Triggers workflow when changes are pushed to 'main'

  # Allows you to manually trigger this workflow from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read  # Grants read access to the repository contents
  pages: write  # Grants write access to GitHub Pages
  id-token: write  # Grants write access to GitHub's identity token

# Allows only one concurrent deployment, skipping queued runs while a deployment is in progress
# However, does NOT cancel in-progress runs to ensure production deployments complete
concurrency:
  group: "pages"  # Defines concurrency group for GitHub Pages deployment
  cancel-in-progress: false  # Prevents cancellation of ongoing deployments

jobs:
  # Single deployment job since we're just deploying static content
  deploy:
    environment:
      name: github-pages  # Defines environment name
      url: ${{ steps.deployment.outputs.page_url }}  # Retrieves deployed page URL
    runs-on: ubuntu-latest  # Runs job on the latest Ubuntu version
    steps:
      - name: Checkout  # Step to check out repository contents
        uses: actions/checkout@v4  # Uses GitHub's checkout action
      
      - name: Setup Pages  # Step to configure GitHub Pages
        uses: actions/configure-pages@v5  # Uses GitHub's configure-pages action
      
      - name: Upload artifact  # Step to upload files for deployment
        uses: actions/upload-pages-artifact@v3  # Uses GitHub's upload action
        with:
          path: '.'  # Uploads entire repository contents
      
      - name: Deploy to GitHub Pages  # Step to deploy to GitHub Pages
        id: deployment  # Sets an ID for the step
        uses: actions/deploy-pages@v4  # Uses GitHub's deployment action